michaelr - TDD, p. 35(all over it) - 36a. The book made a seemingly simple change for the return values of the Fran.times(int) method. Before: Franc times(int multiplier) {...} After:  Money times(int multiplier) {...}
This caused 
runtest:
    [junit] Running MoneyTests
    [junit] Testsuite: MoneyTests
    [junit] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.242 sec
    [junit] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.242 sec
    [junit]
    [junit] Testcase: testDollarMultiplication took 0.015 sec
    [junit] Testcase: testFrancEquality took 0.003 sec
    [junit] Testcase: testDollarFrancInequality took 0.001 sec
    [junit] Testcase: testDollarEquality took 0 sec
    [junit] Testcase: testFrancMultiplication took 0.004 sec
    [junit]     Caused an ERROR
    [junit] Franc.times(I)LFranc;
    [junit] java.lang.NoSuchMethodError: Franc.times(I)LFranc;
    [junit]
    [junit] Test MoneyTests FAILED

RCA on p.35 shows the test failure came from assertEquals(expectedObj, actualObj),
implemented as 
		Franc five = new Franc(5);
		assertEquals(new Franc(10), five.times(2));
Specifically, if I expect a Franc, but get a Money, then I fail.
(A Money is not always a Franc)

If I swap the expected and actual args in the implementation like this ...
		Franc five = new Franc(5);
		assertEquals(five.times(2), new Franc(10));
		///assertEquals(new Franc(10), five.times(2));
... then the test passes because ...
    if I expect a Money, but get a Franc, then I pass.
    (A Franc is ALWAYS a Money.)