michaelr - GOOS, p. 163b; redesign to sniperStateChanged from individual methods nearly complete.
>>>>>>>>>>>>> 2ND REGRESSION CAUGHT!!! <<<<<<<<<<<<<<<

I followed my methodology of running all unit tests. I found that the redesign caused a regression error. I checked this version in to preserve the regression before I fix it.

G:\student\code_practice_junit>ant runtest -DtestClass=SnipersTableModelTests
Buildfile: G:\student\code_practice_junit\build.xml

ensure-test-name:

compile:

compileRT:

runtest-do-it:
    [junit] Running auctionsniper.tests.unit.SnipersTableModelTests
    [junit] Testsuite: auctionsniper.tests.unit.SnipersTableModelTests
    [junit] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.13 sec
    [junit] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.13 sec
    [junit]
    [junit] Testcase: setsSniperValuesInColumns took 0.06 sec
    [junit]     FAILED
    [junit] expected:<BIDDING> but was:<Bidding in auction>
    [junit] junit.framework.AssertionFailedError: expected:<BIDDING> but was:<Bidding in auction>
    [junit]     at org.jmock.integration.junit4.JUnitRuleMockery$1.evaluate(JUnitRuleMockery.java:49)
    [junit]
    [junit] Testcase: hasEnoughColumns took 0 sec
    [junit] Test auctionsniper.tests.unit.SnipersTableModelTests FAILED

git-svn-id: svn://localhost/code_practice/trunk@176 50d94a75-6656-bf47-8487-448895b3180b